@startuml WP#2A-DM
skinparam classAttributeIconSize 0
hide empty members

package "Airport Subdomain (WP#2A)" {

    class Airport <<Aggregate Root>> <<Entity>> {
        - name: String
    }

    class IATACode <<Value Object>> {
        - code: String
    }

    class Location <<Value Object>> {
        -region : String
        - city: String
        - country: String
    }

    class GPSCoordinates <<Value Object>> {
        - latitude: Double
        - longitude: Double
    }

    class Timezone <<Value Object>> {
        - offsetValue: String
    }

    class Runway <<Entity>> {
        - length: Double
    }

    enum Orientation <<ENUM>> {
                N
                S
                E
                W
                NW
                NE
                SW
                SE
    }

    enum AirportStatus <<Enum>> {
        OPERATIONAL
        CLOSED
        MAINTENANCE
    }

    class AirplaneCertification <<Value Object>> {
        -certificationDate : Date
        - modelName : String
    }

    ' Relacionamentos
    Airport "1" *-- "1" IATACode : identified by >
    Airport "1" *-- "1" Location : located at >
    Location "1" *-- "1" GPSCoordinates : has >
    Airport "1" *-- "1" Timezone : operates in >
    Airport "1" *-- "1..*" Runway : contains >
    Runway "1" *-- "1" Orientation : has >
    Airport "1" *-- "1" AirportStatus : has >
    Airport "1" *-- "*" AirplaneCertification : supports >
}

package "Aircraft Subdomain (WP#1)" <<Rectangle>> {
    class "AirplaneModel" as Model <<Aggregate Root>>
}

AirplaneCertification "*" --> "1" Model : references >

@enduml