@startuml
skinparam classAttributeIconSize 0

package "pt.isep.psoft.alsafe.flightroutes.domain" {
    
    class FlightRoute {
        - routeId: String
        - routeStatus: RouteStatus
        + addHistory(author: String)
        + deactivate(author: String)
    }

    class RouteHistory {
        - changeDate: LocalDateTime
        - routeStatus: RouteStatus
        - author: String
        + RouteHistory(author, status)
    }

    enum RouteStatus {
        ACTIVE
        DEACTIVATED
    }
}

FlightRoute *-- "*" RouteHistory : tracks history >
RouteHistory --> "1" RouteStatus : registers state >

@enduml