@startuml SD_US102
autonumber
title Sequence Diagram (SD) - US102: Register Aircraft Instance

actor "ATCC" as ATCC
participant ":AircraftController" as Ctrl
participant ":AircraftService" as Service
participant "modelRepository\n:AircraftModelRepository" as RepoModel
participant "aircraftRepository\n:AircraftRepository" as RepoAir
participant "aircraft\n:Aircraft" as Aircraft

activate ATCC
ATCC -> Ctrl: POST /api/aircrafts (CreateAircraftDTO)
activate Ctrl

Ctrl -> Service: createAircraft(dto)
activate Service

' 1. Verifica se o Modelo de Avião existe na BD
Service -> RepoModel: findByModelName(dto.modelName)
activate RepoModel
RepoModel --> Service: model
deactivate RepoModel

' 2. Criação da Entidade em memória
Service -> Aircraft**: create(dto.registrationNumber, model, dto.manufacturingDate, dto.activeConfigurationName)

' 3. Persistência na Base de Dados
Service -> RepoAir: save(aircraft)
activate RepoAir
RepoAir --> Service: aircraft
deactivate RepoAir

Service --> Ctrl: aircraft
deactivate Service

Ctrl --> ATCC: 201 Created (AircraftResponseDTO)
deactivate Ctrl
deactivate ATCC
@enduml