@startuml US113-CD
skinparam classAttributeIconSize 0

package "api" {
    class FlightRouteController {
        + getRouteById(id: String): ResponseEntity<FlightRouteResponseDTO>
        + searchRoutes(originIata: String, destinationIata: String, pageable: Pageable, assembler: PagedResourcesAssembler): ResponseEntity<PagedModel>
    }
    class FlightRouteResponseDTO
    class FlightRouteModelAssembler {
        + toModel(entity: FlightRoute): FlightRouteResponseDTO
    }
}

package "services" {
    class FlightRouteService {
        + getRouteById(id: String): FlightRoute
        + searchRoutes(originIata: String, destinationIata: String, pageable: Pageable): Page<FlightRoute>
    }
}

package "repositories" {
    interface FlightRouteRepository {
        + findByIdWithHistory(routeId: String): Optional<FlightRoute>
        + findByOrigin_IataCode_Code(origin: String, pageable: Pageable): Page<FlightRoute>
    }
}

package "domain" {
    class FlightRoute <<Aggregate Root>> <<Entity>>
}

FlightRouteController ..> FlightRouteResponseDTO
FlightRouteController --> FlightRouteService : delegates to
FlightRouteController --> FlightRouteModelAssembler : uses
FlightRouteModelAssembler ..> FlightRouteResponseDTO : produces
FlightRouteService --> FlightRouteRepository : uses
FlightRouteService ..> FlightRoute : retrieves

@enduml