@startuml US203-SSD
autonumber
title System Sequence Diagram (SSD) - US203: View Compatible Routes for Aircraft

actor "ATCC" as ATCC

System -> ATCC: Authentication successful
ATCC -> System: Requests compatible routes for an aircraft (registrationNumber)
activate System
System --> ATCC: Returns list of compatible flight routes
deactivate System

@enduml
