@startuml SSD_US104
autonumber
title System Sequence Diagram (SSD) - US104: Search for Aircraft

actor "ATCC" as Actor
participant "AISafe System" as System <<System>>

activate Actor

Actor -> System: requests to search aircraft by model, status, or manufacturing year
activate System

System --> Actor: retrieves and returns a list of matching aircraft (200 OK)
deactivate System

deactivate Actor
@enduml