@startuml US103-SSD
autonumber
title System Sequence Diagram (SSD) - US103: View Aircraft Details

actor "ATCC" as Actor
participant ":System" as System

activate Actor
Actor -> System: initiates viewing aircraft details
activate System
System --> Actor: requests the aircraft registration number
deactivate System

Actor -> System: inputs the requested data
activate System
System --> Actor: returns the aircraft details (200 OK)
deactivate System
deactivate Actor
@enduml