@startuml SSD_US103
autonumber
title System Sequence Diagram (SSD) - US103: View Aircraft Details

actor "Backoffice Operator / ATCC" as Actor
participant "AISafe System" as System <<System>>

activate Actor

Actor -> System: requests aircraft details for a specific registration number
activate System

System --> Actor: retrieves and returns the aircraft details (200 OK)
deactivate System

deactivate Actor
@enduml