@startuml
skinparam classAttributeIconSize 0

package "pt.isep.psoft.alsafe.flightroutes.api" {
    class FlightRouteController {
        + createRoute(dto: CreateFlightRouteDTO): ResponseEntity
    }
    class CreateFlightRouteDTO {
        - originIata: String
        - destinationIata: String
        - distance: Double
        - estimatedFlightTime: Integer
        - minRangeRequired: Double
        - minCapacityRequired: Integer
    }
}

package "pt.isep.psoft.alsafe.flightroutes.services" {
    class FlightRouteService {
        + createFlightRoute(dto: CreateFlightRouteDTO): FlightRouteResponseDTO
    }
}

package "pt.isep.psoft.alsafe.airportmanagement.services" {
    class AirportService {
        + getAirportDetails(iata: String): Airport
    }
}

package "pt.isep.psoft.alsafe.flightroutes.repositories" {
    interface FlightRouteRepository {
        + save(route: FlightRoute): FlightRoute
    }
}

package "pt.isep.psoft.alsafe.flightroutes.domain" {
    class FlightRoute {
        - routeId: RouteId
        - version: Long
        - distance: Double
        - estimatedFlightTime: Integer
        - routeStatus: RouteStatus
        + FlightRoute(id: String, origin: Airport, dest: Airport, distance: Double, time: Integer, req: RouteRequirement, author: String)
    }
    
    class RouteId <<Value Object>> {
        - id: String
        + RouteId(id: String)
    }
    
    class RouteRequirement <<Value Object>> {
        - minRangeRequired: Double
        - minCapacityRequired: Integer
        + RouteRequirement(range: Double, capacity: Integer)
    }
}

FlightRouteController .right.> CreateFlightRouteDTO
FlightRouteController --> FlightRouteService : uses
FlightRouteService --> AirportService : uses
FlightRouteService --> FlightRouteRepository : uses
FlightRouteService ..> FlightRoute : creates
FlightRoute "1" *-- "1" RouteId : identified by >
FlightRoute "1" *-- "1" RouteRequirement : contains >

@enduml