@startuml US114-SD
autonumber
actor "ATCC / BO" as Actor
participant "FlightRouteController" as Ctrl
participant "FlightRouteService" as Service
participant "FlightRouteRepository" as Repo
participant "PagedResourcesAssembler" as PagedAssembler

activate Actor
Actor -> Ctrl: GET /api/flight-routes?originIata={O}&destinationIata={D}&page=0&size=10
activate Ctrl

Ctrl -> Service: searchRoutes(originIata, destinationIata, pageable)
activate Service

note right of Service: IATA codes are sanitized\n(uppercased) before querying

alt originIata != null && destinationIata != null
    Service -> Repo: findByOrigin_IataCode_CodeAndDestination_IataCode_Code(origin, dest, pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
else originIata != null
    Service -> Repo: findByOrigin_IataCode_Code(origin, pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
else destinationIata != null
    Service -> Repo: findByDestination_IataCode_Code(dest, pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
else neither provided
    Service -> Repo: findAll(pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
end

Service --> Ctrl: Page<FlightRoute>
deactivate Service

Ctrl -> PagedAssembler: toModel(page, flightRouteModelAssembler)
activate PagedAssembler
note right of PagedAssembler: Maps entities to DTOs using your Assembler,\nand appends HATEOAS pagination links\n(self, next, prev, first, last)
PagedAssembler --> Ctrl: PagedModel<EntityModel<FlightRouteResponseDTO>>
deactivate PagedAssembler

Ctrl --> Actor: 200 OK (PagedModel)
deactivate Ctrl
deactivate Actor
@enduml