@startuml
autonumber
actor "ATCC" as Actor
participant ":FlightRouteController" as Ctrl
participant ":FlightRouteService" as Service
participant "routeRepository\n:FlightRouteRepository" as Repo

activate Actor
Actor -> Ctrl: GET /api/flight-routes?originIata={iata}&destinationIata={iata}
activate Ctrl

Ctrl -> Service: searchRoutes(originIata, destinationIata, pageable)
activate Service

note right of Service: 21/20 Touch:\noriginIata.toUpperCase()\ndestinationIata.toUpperCase()
Service -> Service: Input Sanitization (Case-Insensitivity)

alt originIata != null && destinationIata != null
    Service -> Repo: findByOrigin_IataCode_CodeAndDestination_IataCode_Code(..., pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
else originIata != null
    Service -> Repo: findByOrigin_IataCode_Code(..., pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
else destinationIata != null
    Service -> Repo: findByDestination_IataCode_Code(..., pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
else neither provided
    Service -> Repo: findAll(pageable)
    activate Repo
    Repo --> Service: Page<FlightRoute>
    deactivate Repo
end

Service --> Ctrl: routePage
deactivate Service

Ctrl -> Ctrl: routePage.map(FlightRouteResponseDTO::new)
note right of Ctrl: Maps Page of Entities to Page of DTOs

Ctrl --> Actor: 200 OK (Page<FlightRouteResponseDTO>)
deactivate Ctrl
deactivate Actor
@enduml