@startuml US114-CD
skinparam classAttributeIconSize 0

package "api" {
    class FlightRouteController {
        + searchRoutes(originIata: String, destinationIata: String, pageable: Pageable, assembler: PagedResourcesAssembler): ResponseEntity<PagedModel>
    }
    class FlightRouteResponseDTO
    class FlightRouteModelAssembler {
        + toModel(entity: FlightRoute): FlightRouteResponseDTO
    }
}

package "services" {
    class FlightRouteService {
        + searchRoutes(originIata: String, destinationIata: String, pageable: Pageable): Page<FlightRoute>
    }
}

package "repositories" {
    interface FlightRouteRepository {
        + findByOrigin_IataCode_CodeAndDestination_IataCode_Code(origin: String, dest: String, pageable: Pageable): Page<FlightRoute>
        + findByOrigin_IataCode_Code(origin: String, pageable: Pageable): Page<FlightRoute>
        + findByDestination_IataCode_Code(dest: String, pageable: Pageable): Page<FlightRoute>
        + findAll(pageable: Pageable): Page<FlightRoute>
    }
}

package "domain" {
    class FlightRoute <<Aggregate Root>> <<Entity>>
}

FlightRouteController ..> FlightRouteResponseDTO
FlightRouteController --> FlightRouteService : delegates to
FlightRouteController --> FlightRouteModelAssembler : uses
FlightRouteModelAssembler ..> FlightRouteResponseDTO : produces
FlightRouteService --> FlightRouteRepository : uses
FlightRouteService ..> FlightRoute : retrieves
@enduml