@startuml US104-SSD
autonumber
title Sequence Diagram (SD) - US104: Search Aircraft

actor "ATCC" as ATCC
participant ":AircraftController" as Ctrl
participant ":AircraftService" as Service
participant "repository\n:AircraftRepository" as Repo

activate ATCC
ATCC -> Ctrl: GET /api/aircrafts?modelName={model}&status={status}
activate Ctrl

Ctrl -> Service: searchAircrafts(modelName, status)
activate Service

Service -> Repo: findByModelNameAndStatus(modelName, status)
activate Repo
Repo --> Service: List<Aircraft>
deactivate Repo

Service --> Ctrl: List<Aircraft>
deactivate Service

Ctrl --> ATCC: 200 OK (List<AircraftResponseDTO>)
deactivate Ctrl
deactivate ATCC
@enduml