@startuml US104-SSD
autonumber
title System Sequence Diagram (SSD) - US104: Search Aircraft

actor "ATCC" as Actor
participant ":System" as System

activate Actor
Actor -> System: initiates aircraft search
activate System
System --> Actor: requests search criteria (e.g., model name, status)
deactivate System

Actor -> System: inputs the requested criteria
activate System
System --> Actor: returns the list of matching aircraft (200 OK)
deactivate System
deactivate Actor
@enduml