@startuml SSD_US102
autonumber
title System Sequence Diagram (SSD) - US102: Register a Specific Aircraft Instance

actor "Air Transport Company Collaborator (ATCC)" as Actor
participant "AISafe System" as System <<System>>

activate Actor

Actor -> System: inputs new aircraft details (registration number, model name, manufacturing date, active configuration)
activate System

System --> Actor: validates data, registers aircraft instance and returns success confirmation (201 Created)
deactivate System

deactivate Actor
@enduml