@startuml US105-SSD
autonumber
title System Sequence Diagram (SSD) - US105: Update Operational Status

actor "ATCC" as Actor
participant ":System" as System

activate Actor
Actor -> System: initiates the update of an aircraft's operational status
activate System
System --> Actor: requests the registration number and the new status
deactivate System

Actor -> System: inputs the requested data
activate System
System --> Actor: confirms the update and returns the updated details (200 OK)
deactivate System
deactivate Actor
@enduml